### ISSUE TITLE
seed を作る

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#10]
サービスを起動するためのデータを事前に作っておく機能として seed というものがあります。
チームで開発を始めると、それぞれのメンバーでデータを作るのは無駄なので、このような情報を簡単に作成できるようにします。

まずはしらべて一度やってみてくださいー。

**Comment by tedexample** [comment]
userとpostの機能がまともに走ってるカラムのみですが、簡単にseedのデータを実装してみました。

**Comment by ms2sato** [comment]
@tedexample 承知です！ likeやcomment については実装しつつ、追加するようにしてくださいねー・

**Comment by ms2sato** [comment]
一旦closeします。
