### ISSUE TITLE
DBをpostgresにして、foreign_key ができているか確かめる

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#21]

**Comment by tedexample** [comment]
スキーマを見るとpostgresをenable_extentionと出ていたのでDBの移行は成功かと思いますが、foreign_keyはスキーマに出ていませんです。一度見ていただけませんか？

**Comment by tedexample** [comment]
すいません！foreign_key出てました！スキーマの一番下に並んでました！
なのでこのissue完了かと。

**Comment by tedexample** [comment]
#23 で対応

**Comment by ms2sato** [comment]
@tedexample Good! これはこれでOKとして、 #36 を作ってみました。こういうのもありますよってことで。
