### ISSUE TITLE
scssのクラス名のアンダースコアを修正

### ISSUE THREAD

**Issue by tedexample** [tedexample/shumishareca#28]
#16 の指摘点

**Comment by tedexample** [comment]
Edit comments #22　で修正

**Comment by ms2sato** [comment]
@tedexample この点は修正して欲しいの前に、なにかルール作っているのかなというところを聞いてみたかったです。何か決めてます？まだハイフンとアンダースコア混ざってますよね。統一したい感じかな？

**Comment by tedexample** [comment]
ルールは何も決めていなくて、アンダースコアは使わずにハイフンを使うのに統一するつもりで書いてました。

**Comment by ms2sato** [comment]
@tedexample 承知ですー。ではアンダースコアはtypoってことなんですね。承知です。
