### ISSUE TITLE
uniqueにできるforeign_key に対応する

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#36]
このサービスならLikeは「一人のユーザー、一つのPost」に対して1つしか作成されないので、IDの組み合わせでユニークになりますよね（user_Idとpost_idの組み合わせが重複することがありえない）

これをDBで守ることにして、foreign_key いれてみましょう。
また、モデルにも同様の uniqueいれてください（実はこれは一長一短ありますが、まずは知ることが大事かと）。

**Comment by tedexample** [comment]
#40 にて対応しています。
