### ISSUE TITLE
モデルのspecを書く

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#37]
Everyday Rails を紹介したと思いますが、読み進めてますかね？
もしもできそうならモデルのspecを書いてみるのも良いと思っています。
Postのバリデーションくらいから腕試しを始めると良さそうです。

できそうでしょうか？

**Comment by tedexample** [comment]
#48 の対応策
PR側にもコメント入れていますが、everyday rails を読んで参照できる範囲を人まず実装してみました。
