### ISSUE TITLE
[落ち着いたら] Post has_many Category にする

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#4]
この場合、 Postについてのカテゴリーをテーブルにして複数持つのが一般的です。「多」を1カラム内に持つのはよく無い手法（アンチパターン）と呼ばれています。

**Comment by tedexample** [comment]
accepts_nested_attributes_for :categories　をPostモデルに定義して、viewのformに field_for ...でフォームのコードを書いても表示されずで止まっています。。。

**Comment by ms2sato** [comment]
@tedexample こういう時は、一度PullRequest作ってください。そしてタイトルに [WIP] とつけてくだされ（作業中の意味です）。

その上で私にメンションしてヘルプを依頼するとこちらも書いたコードベースで話ができるので色々と都合が良いです。
