### ISSUE TITLE
Likeの作成処理を修正する

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#42]
https://github.com/tedexample/shumishareca/blob/master/app/controllers/likes_controller.rb#L6

- current_user から辿るようにしましょう。
- uniqueの制約もあり、この作成が失敗する可能性ができてきました。
  - どういう時に失敗するでしょうか
  - 上記を踏まえて、どのように対応しましょう。提案してください。

**Comment by tedexample** [comment]
#44 で対応
