### ISSUE TITLE
Postに状態を持たせる

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#43]
`enum` の機能を使って以下を実現してください。

- Postが状態を持つ（下書きと公開とか、非公開とか。この辺りはお任せします）
- Postが作られた時にデフォルトで状態は何か決めてください。マイグレーションの中で値を指定します。
- Postのフォームで状態を指定できるようにする
- 公開状態のものだけが一覧へ表示されるようにする

**Comment by tedexample** [comment]
#45 で対応しマージ済みです。

**Comment by ms2sato** [comment]
@tedexample Issueは担当者なので、 このリポジトリでは基本的に @tedexample さんから動くことはないですよ。終わったらCloseして大丈夫です。
