### ISSUE TITLE
コメントのコメント主を取得できない

### ISSUE THREAD

**Issue by tedexample** [tedexample/shumishareca#46]
usersテーブルとpostsテーブルにcommentsテーブルが中間テーブルの関係にある状態で
@post.comments.each do |comment|
  comment.user.name
end
のように comment.userが取り出せない（上の図だとundifind method　user　とエラーがでる）

issueで直接上がっていない＋PRがまだちゃんとできなかった頃の問題で現在も残っているので忘れないようにissueであげておきます。

**Comment by tedexample** [comment]
#49 で対応

**Comment by tedexample** [comment]
@ms2sato こちらもcloseかと思います。

**Comment by ms2sato** [comment]
OK
