### ISSUE TITLE
コメント入力時のエラーが表示できない

### ISSUE THREAD

**Issue by tedexample** [tedexample/shumishareca#47]
#46同様こちらも防備です。
form_withやform_forのかっこ内に指定するインスタンスのルールの理解が浅いのでリソースをネストしたインスタンス（今回でいうコメント）の入力に対するエラーの表示がうまくいかない、もしくはundifind methodとエラーが出てしまう。
・id、○○_idの指定の仕方が間違っていると考えてますが、しっかり腹落ちできていないですのでそこをissueとしてあげておきます。

**Comment by tedexample** [comment]
#49 で対応

**Comment by tedexample** [comment]
@ms2sato #49がマージされたのでcloseでしょうか？

**Comment by ms2sato** [comment]
OK
