### ISSUE TITLE
画像アップロードのUIの調整

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#54]
ref https://github.com/tedexample/shumishareca/pull/41#discussion_r199767607

既にファイルがアップされている場合に、下記の動作をするようにしましょう。

- ファイル削除用のUIが表示され、ファイルを削除することができる
- サムネイルとして小さな画像が表示される

**Comment by tedexample** [comment]
@ms2sato 
【仕様の質問】
これは編集画面についてですよね？

**Comment by ms2sato** [comment]
@tedexample YESです！編集画面のFORMへの要望です。

**Comment by tedexample** [comment]
#56 のPRで対応

**Comment by tedexample** [comment]
#61 PRをマージしたのでcloseしますね。
