### ISSUE TITLE
画像アップロードの際にバリデーションが起きても画像が消えないようにする

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#55]
例えばPostsのタイトルを未入力にしてバリデーションエラーが起きた場合などに、今アップしようとしていたファイルが消えてしまいます。

このファイルがちゃんと残るようにしましょう。

**Comment by tedexample** [comment]
#54 のPRとコンフリクト作ってしまいそうな気がするので#54がマージした後にやります。

**Comment by tedexample** [comment]
#61 で対応
