### ISSUE TITLE
[git] PullRequestを作ってみる

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#6]
まずは一度放り投げてみます。できそうか調べてみてください。できそうならPullRequestを実際に作ってみてください。

**Comment by tedexample** [comment]
できているはずです。昨日ご指摘いただいたのをpull requestしようとしましたが、ローカルのmasterでpushしちゃったので練習がてらreadmeファイルを編集してpull requestを作っておきました。

**Comment by ms2sato** [comment]
よくできました！
